/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as DashboardRouteImport } from "./routes/dashboard"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as IntakeIndexRouteImport } from "./routes/intake/index"
import { Route as FoodItemsIndexRouteImport } from "./routes/food-items/index"
import { Route as CategoriesIndexRouteImport } from "./routes/categories/index"
import { Route as IntakeNewRouteImport } from "./routes/intake/new"
import { Route as FoodItemsNewRouteImport } from "./routes/food-items/new"
import { Route as FoodItemsFoodItemIdEditRouteImport } from "./routes/food-items/$foodItemId.edit"

const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: "/intake/",
  path: "/intake/",
  getParentRoute: () => rootRouteImport,
} as any)
const FoodItemsIndexRoute = FoodItemsIndexRouteImport.update({
  id: "/food-items/",
  path: "/food-items/",
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: "/categories/",
  path: "/categories/",
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeNewRoute = IntakeNewRouteImport.update({
  id: "/intake/new",
  path: "/intake/new",
  getParentRoute: () => rootRouteImport,
} as any)
const FoodItemsNewRoute = FoodItemsNewRouteImport.update({
  id: "/food-items/new",
  path: "/food-items/new",
  getParentRoute: () => rootRouteImport,
} as any)
const FoodItemsFoodItemIdEditRoute = FoodItemsFoodItemIdEditRouteImport.update({
  id: "/food-items/$foodItemId/edit",
  path: "/food-items/$foodItemId/edit",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardRoute
  "/food-items/new": typeof FoodItemsNewRoute
  "/intake/new": typeof IntakeNewRoute
  "/categories/": typeof CategoriesIndexRoute
  "/food-items/": typeof FoodItemsIndexRoute
  "/intake/": typeof IntakeIndexRoute
  "/food-items/$foodItemId/edit": typeof FoodItemsFoodItemIdEditRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardRoute
  "/food-items/new": typeof FoodItemsNewRoute
  "/intake/new": typeof IntakeNewRoute
  "/categories": typeof CategoriesIndexRoute
  "/food-items": typeof FoodItemsIndexRoute
  "/intake": typeof IntakeIndexRoute
  "/food-items/$foodItemId/edit": typeof FoodItemsFoodItemIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardRoute
  "/food-items/new": typeof FoodItemsNewRoute
  "/intake/new": typeof IntakeNewRoute
  "/categories/": typeof CategoriesIndexRoute
  "/food-items/": typeof FoodItemsIndexRoute
  "/intake/": typeof IntakeIndexRoute
  "/food-items/$foodItemId/edit": typeof FoodItemsFoodItemIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/dashboard"
    | "/food-items/new"
    | "/intake/new"
    | "/categories/"
    | "/food-items/"
    | "/intake/"
    | "/food-items/$foodItemId/edit"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/dashboard"
    | "/food-items/new"
    | "/intake/new"
    | "/categories"
    | "/food-items"
    | "/intake"
    | "/food-items/$foodItemId/edit"
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/food-items/new"
    | "/intake/new"
    | "/categories/"
    | "/food-items/"
    | "/intake/"
    | "/food-items/$foodItemId/edit"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FoodItemsNewRoute: typeof FoodItemsNewRoute
  IntakeNewRoute: typeof IntakeNewRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  FoodItemsIndexRoute: typeof FoodItemsIndexRoute
  IntakeIndexRoute: typeof IntakeIndexRoute
  FoodItemsFoodItemIdEditRoute: typeof FoodItemsFoodItemIdEditRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/intake/": {
      id: "/intake/"
      path: "/intake"
      fullPath: "/intake/"
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/food-items/": {
      id: "/food-items/"
      path: "/food-items"
      fullPath: "/food-items/"
      preLoaderRoute: typeof FoodItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/categories/": {
      id: "/categories/"
      path: "/categories"
      fullPath: "/categories/"
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/intake/new": {
      id: "/intake/new"
      path: "/intake/new"
      fullPath: "/intake/new"
      preLoaderRoute: typeof IntakeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/food-items/new": {
      id: "/food-items/new"
      path: "/food-items/new"
      fullPath: "/food-items/new"
      preLoaderRoute: typeof FoodItemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/food-items/$foodItemId/edit": {
      id: "/food-items/$foodItemId/edit"
      path: "/food-items/$foodItemId/edit"
      fullPath: "/food-items/$foodItemId/edit"
      preLoaderRoute: typeof FoodItemsFoodItemIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FoodItemsNewRoute: FoodItemsNewRoute,
  IntakeNewRoute: IntakeNewRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  FoodItemsIndexRoute: FoodItemsIndexRoute,
  IntakeIndexRoute: IntakeIndexRoute,
  FoodItemsFoodItemIdEditRoute: FoodItemsFoodItemIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
